<a href="https://colab.research.google.com/github/Abhishekkatkar123/python-/blob/main/PYTHON_NUMPY_ASSIGNMENT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#seq from 0 to 100 with gaps of 2 using arage function
import numpy as np
arr=np.arange(0,100,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
#vector is 1d array
#argmax() to find max element
arr_vector=np.array([1,2,3,4,5,6,7,8,9,10])
max_index=arr_vector.argmax()
arr_vector[max_index]=0
print(arr_vector)


[1 2 3 4 5 6 7 8 9 0]


In [ ]:
#iris data
iris_data=np.genfromtxt('iris.csv',delimiter=',',skip_header=1)
data=iris_data[(iris_data[:,2]>1.5)& (iris_data[:,0]<5.0)]
print(data)

[[4.8 3.4 1.6 0.2 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [4.9 2.4 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]]


In [ ]:
sepal_length=iris_data[:,0]
mim=np.min(sepal_length)
maxx=np.max(sepal_length)
sd=np.std(sepal_length)
print(mim)
print(maxx)
print(sd)

4.3
7.9
0.8253012917851409


In [ ]:
#normaize between 0 and 1 using min max scaling formula
#length-min.length/max.length-min.length
sepal_length=iris_data[:,0]
normalized=(sepal_length-np.min(sepal_length))/(np.max(sepal_length)-np.min(sepal_length))
print(normalized)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [ ]:

petal_length_column = iris_data[:, 2]

# Randomly insert null values
null_indices = np.random.choice(len(petal_length_column), size=int(0.1 * len(petal_length_column)), replace=False)
petal_length_column[null_indices] = np.nan

# Print the array with null values
print("Petal Length with Null Values:")
print(petal_length_column)

Petal Length with Null Values:
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 nan 1.6 1.4 nan 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 nan 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.4 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 nan 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 nan nan 4.4 4.8 nan 4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 nan 4.6 4.  nan 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 nan 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 nan 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 nan 5.6 nan 5.1 5.9
 nan 5.2 5.  5.2 5.4 nan]


In [ ]:
#missing values
missing_value=np.where(np.isnan(petal_length_column))
print(missing_value)

(array([ 10,  13,  25,  46,  73,  74,  77,  90,  93, 112, 126, 139, 141,
       144, 149]),)


In [ ]:
#removing null values column

# Assuming iris_data is already loaded
iris_data_no_null = iris_data[~np.isnan(iris_data).any(axis=1)]

# Print the resulting array
print("Iris Data without Rows Containing Null Values:")
print(iris_data_no_null)

Iris Data without Rows Containing Null Values:
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 

In [ ]:
unique=np.unique(iris_data,return_counts=True)
print(unique)

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5,
       1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8,
       2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1,
       4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4,
       5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7,
       6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9, nan]), array([50,  5, 29,  7,  7,  1,  1, 58,  3,  7, 20, 21, 24,  9,  6, 12,  7,
       57,  6,  6, 12,  6, 11,  5,  9, 14, 10, 27, 11, 13,  7, 12,  8,  5,
        4,  7,  5,  6,  4,  5,  2,  7,  9,  7,  6,  8, 11, 13, 15,  6,  3,
        7,  9, 12, 10, 10,  5,  8,  9,  4, 10,  8,  5,  3, 10,  3,  5,  1,
        1,  3,  1,  1,  1,  4,  1, 15]))


In [ ]:


# Assuming iris_data is already loaded
species_column = iris_data[:, -1]  # Assuming the species column is the last column

# Count number of rows per species using numpy
unique_species, counts = np.unique(species_column, return_counts=True)

# Create a dictionary to display the counts for each unique species
species_counts = dict(zip(unique_species, counts))

# Print the counts
print("Number of Rows per Species:")
print(species_counts)

Number of Rows per Species:
{0.0: 50, 1.0: 50, 2.0: 50}
